// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYrMULsVlrnWd25VPXXIB6YTRyR2GDm9o',
    appId: '1:751832243254:web:4c5e90706ec399aa2e0c97',
    messagingSenderId: '751832243254',
    projectId: 'skillapp-c2f86',
    authDomain: 'skillapp-c2f86.firebaseapp.com',
    storageBucket: 'skillapp-c2f86.appspot.com',
    measurementId: 'G-TDNNNM0EYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6_iPCwibAo5JLNwRaA93kI0bn1u4mlf0',
    appId: '1:751832243254:android:f76a4212b283f6c92e0c97',
    messagingSenderId: '751832243254',
    projectId: 'skillapp-c2f86',
    storageBucket: 'skillapp-c2f86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh2i2NzsCOp73Ro0D1DG1eN_j24c4cVvA',
    appId: '1:751832243254:ios:a7bdadfaab072bdb2e0c97',
    messagingSenderId: '751832243254',
    projectId: 'skillapp-c2f86',
    storageBucket: 'skillapp-c2f86.appspot.com',
    iosClientId: '751832243254-um1jorkpu20ge10fjsq7l7vmtqa1afet.apps.googleusercontent.com',
    iosBundleId: 'com.nill.sk',
  );
}
